import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

def plot_ablations():
    """
    Generates comparative bar charts for the ablation study.
    
    This script reads the 'ablation_results.csv' file (produced by ablation_study.py)
    or uses hardcoded fallback data if the file is missing. It visualizes three key 
    impact axes defined in the report:
    1. Model Capacity (Number of Filters)
    2. Kernel Selectivity (Alpha Parameter)
    3. Unsupervised Learning Budget (Number of Patches)
    
    The resulting figure is saved as 'ablation_study.png' for inclusion in the LaTeX report.
    """
    
    # Try to read the CSV generated by the ablation script
    try:
        df = pd.read_csv('ablation_results.csv')
        # Map specific experiment names to types for grouping
        type_mapping = {
            'Baseline': 'Reference',
            'Low Capacity': 'Capacity', 'High Capacity': 'Capacity',
            'Low Selectivity (Alpha=0.5)': 'Selectivity', 'High Selectivity (Alpha=1.5)': 'Selectivity',
            'Low Budget (10k)': 'Budget', 'High Budget (200k)': 'Budget'
        }
        df['Type'] = df['Experiment'].map(type_mapping)
    except FileNotFoundError:
        print("Warning: 'ablation_results.csv' not found. Using hardcoded values from previous run.")
        data = {
            'Experiment': [
                'Baseline', 'Low Capacity', 'High Capacity', 
                'Low Selectivity (Alpha=0.5)', 'High Selectivity (Alpha=1.5)', 
                'Low Budget (10k)', 'High Budget (200k)'
            ],
            'Accuracy': [32.07, 31.32, 27.35, 25.35, 37.30, 30.32, 28.30],
            'Type': [
                'Reference', 'Capacity', 'Capacity', 
                'Selectivity', 'Selectivity', 
                'Budget', 'Budget'
            ]
        }
        df = pd.DataFrame(data)

    # Setup plot style
    sns.set_theme(style="whitegrid")
    fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=True)
    
    # Color palette for distinct visualization
    colors = {"Reference": "gray", "Capacity": "blue", "Selectivity": "green", "Budget": "orange"}

    # --- Plot 1: Capacity Impact ---
    df_cap = df[df['Type'].isin(['Reference', 'Capacity'])].copy()
    df_cap['Order'] = df_cap['Experiment'].map({
        'Low Capacity': 1, 'Baseline': 2, 'High Capacity': 3
    })
    df_cap = df_cap.sort_values('Order')
    
    sns.barplot(ax=axes[0], x='Experiment', y='Accuracy', hue='Type', data=df_cap, palette=colors, dodge=False)
    axes[0].set_title('Impact of Model Capacity (Filters)')
    axes[0].set_xlabel('')
    axes[0].set_ylabel('Test Accuracy (%)')
    axes[0].bar_label(axes[0].containers[0], fmt='%.1f%%')
    
    # Correction: Set ticks explicitly before labels
    axes[0].set_xticks(range(3))
    axes[0].set_xticklabels(['Low\n(32-64)', 'Baseline\n(64-128)', 'High\n(128-256)'])
    if axes[0].get_legend(): axes[0].legend_.remove()

    # --- Plot 2: Selectivity Impact ---
    df_sel = df[df['Type'].isin(['Reference', 'Selectivity'])].copy()
    df_sel['Order'] = df_sel['Experiment'].map({
        'Low Selectivity (Alpha=0.5)': 1, 'Baseline': 2, 'High Selectivity (Alpha=1.5)': 3
    })
    df_sel = df_sel.sort_values('Order')

    sns.barplot(ax=axes[1], x='Experiment', y='Accuracy', hue='Type', data=df_sel, palette=colors, dodge=False)
    axes[1].set_title('Impact of Kernel Selectivity (Alpha)')
    axes[1].set_xlabel('')
    axes[1].set_ylabel('')
    axes[1].bar_label(axes[1].containers[0], fmt='%.1f%%')
    
    # Correction: Set ticks explicitly before labels
    axes[1].set_xticks(range(3))
    axes[1].set_xticklabels(['Low\n(0.5)', 'Baseline\n(1.0)', 'High\n(1.5)'])
    if axes[1].get_legend(): axes[1].legend_.remove()

    # --- Plot 3: Budget Impact ---
    df_bud = df[df['Type'].isin(['Reference', 'Budget'])].copy()
    df_bud['Order'] = df_bud['Experiment'].map({
        'Low Budget (10k)': 1, 'Baseline': 2, 'High Budget (200k)': 3
    })
    df_bud = df_bud.sort_values('Order')

    sns.barplot(ax=axes[2], x='Experiment', y='Accuracy', hue='Type', data=df_bud, palette=colors, dodge=False)
    axes[2].set_title('Impact of Unsupervised Budget (Patches)')
    axes[2].set_xlabel('')
    axes[2].set_ylabel('')
    axes[2].bar_label(axes[2].containers[0], fmt='%.1f%%')
    
    # Correction: Set ticks explicitly before labels
    axes[2].set_xticks(range(3))
    axes[2].set_xticklabels(['Low\n(10k)', 'Baseline\n(100k)', 'High\n(200k)'])
    if axes[2].get_legend(): axes[2].legend_.remove()

    plt.tight_layout()
    plt.savefig('ablation_study.png', dpi=300)
    print("Success: Plot saved as 'ablation_study.png'")

if __name__ == "__main__":
    plot_ablations()